#+title: GNOME Catppuccin

This script edits the standard GNOME Shell stylesheets to apply the [[https://catppuccin.com][Catppuccin]] colorscheme.
It generates a theme to be used with the [[https://extensions.gnome.org/extension/19/user-themes][User Themes]] extension.

The theme is packaged for Nix (see [[default.nix]]). If you use NixOS or home-manager, you should be able to install it like any other GNOME theme.

** Catppuccin Flavor

Catppuccin has four flavors: a light theme (Latte) and three dark ones (Frappe, Macchiato, Mocha).
*This scripts builds Mocha*, the darkest, because it is the one I use.

However, you can easily edit [[palette.scss]] to change all mentions of Mocha to another flavor if you so desire. There is a section at the end called "GNOME Color Palette" with stuff like
#+begin_src scss
$yellow_1: $mocha-yellow;
#+end_src
You can simply replace all these with lines like
#+begin_src scss
$yellow_1: $frappe-yellow;
#+end_src
You will also have to make similar simple edits to [[colors.scss.patch]] and [[default-colors.scss.patch]].

Moreover, this script can be used to change the GNOME theme with any color palette. Again, just edit the three files mentionned above with the colors you wish.


** For Nix users

For NixOS/home-manager users: add something like this to an overlay
#+begin_src nix
gnome-catppuccin =
  let
    src = pkgs.fetchFromGitHub {
      owner = "elisesouche";
      repo = "gnome-catppuccin";
      rev = "v1.0";
      hash = "sha256-R/pIVO8I3d5cAhgGSHthOpjHEo1Oxbaepb30raxWRnc=";
      fetchSubmodules = true;
    };
  in pkgs.callPackage "${src}" {};
#+end_src

and then simply add
#+begin_src
home.packages = [ pkgs.gnome-catppuccin ];
#+end_src
to a home-manager module. The User Themes extension can then be used to apply the theme.

** Usage for non-Nix users

*** Dependencies

You need Python (I use 3.13) with the libraries =libsass= and =diff_match_patch=.
If you are on Nix, a [[shell.nix]] is provided.

*** Generating the theme

Clone this repository:
#+begin_src shell
git clone --depth=1 https://github.com/elisesouche/gnome-catppuccin
cd gnome-catppuccin
#+end_src

Build:
#+begin_src shell
./build.py
#+end_src

The theme is built in =./_build/theme=.

*** Installing the theme


The theme is located at =./_build/theme=.
You can simply copy its content or symlink it to =~/.themes/gnome-catppuccin= (or some other name).
Then you can apply the theme the regular way from the GNOME Extensions app!.
